#!/bin/bash -ex

dl() {
    [ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
    cd $2; curl -L -f -O $PROXY $1; cd -
}

# Download Moodle
URL="https://github.com/edurenye/moodle/archive/master.zip"
mkdir /usr/local/src/moodle
dl $URL /usr/local/src/moodle

# Download Moosh
URL="https://github.com/tmuras/moosh/archive/master.zip"
mkdir /usr/local/src/moosh
dl $URL /usr/local/src/moosh

# Download Composer
URL="https://getcomposer.org/installer"
mkdir /usr/local/src/composer
dl $URL /usr/local/src/composer

